language: ruby

cache: bundler

sudo: false

rvm: 2.2.2

gemfile: gemfiles/4.2.4.gemfile

env: DB=postgres

before_install:
  - git submodule update --init --recursive

before_script:
  - bundle install

script: "RAILS_ENV=test bundle exec rake"
